[package]
name = "fits-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
fits = { path = "../fits" }
leptos = { version = "0.6.11", features = ["csr", "nightly"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
